# SPDX-FileCopyrightText: math-spec Contributors
#
# SPDX-License-Identifier: MIT

"""The shell front — `python -m math_spec <verb> model.yaml`.

What is checked here is the *design* rather than argparse: that the typeset
verbs are read off `FORMATS` rather than listed twice, that `check` is the
language's verdict and its advice with no consumer installed, that the front
costs no dependency, that no verb binds data, and that a format nothing can
render is refused rather than written as an empty file.

`main` takes its argv and `parser` hands back the verbs, so none of this needs a
subprocess or a scrape of help text.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

import pytest

import math_spec.__main__ as front
from math_spec.typesetting import FORMATS
from tests.typesetting import golden

#: The golden model, not `examples/dispatch.yaml`: the CLI travels with the
#: renderer and this fixture travels with both, where the gallery stays.
MODEL = str(golden.MODEL)


def _verbs() -> dict[str, argparse.ArgumentParser]:
    """The subcommands the front actually registered, each with its parser.

    Read off the parser rather than the ``--help`` text: a format named in a
    help *sentence* would satisfy a substring check without a verb existing.
    """
    for action in front.parser()._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action.choices
    raise AssertionError('the front registered no subcommands at all')


def test_the_verbs_are_check_and_the_formats_and_nothing_else():
    """The one claim the module makes about itself, in both directions.

    The typeset verbs are built by looping over `FORMATS`, so a new format
    arrives with its verb already written and there is no second list to
    forget. A verb hand-added here, or a format quietly dropped, breaks this.
    """
    assert set(_verbs()) == set(FORMATS) | {'check'}


UNUSED_DIMENSION = """
dimensions:
  g: {dtype: str}
  spare: {dtype: str}
parameters:
  c: {dims: [g]}
variables:
  p: {foreach: [g], bounds: {lower: 0}}
objective: {sense: minimize, expression: "sum(p * c)"}
"""


def test_check_prints_nothing_for_a_clean_file(capsys):
    assert front.main(['check', str(Path(__file__).resolve().parents[2] / 'examples' / 'dispatch.yaml')]) == 0
    assert capsys.readouterr() == ('', ''), 'no advice, no output'


def test_check_prints_advice_and_does_not_fail(tmp_path, capsys):
    model = tmp_path / 'm.yaml'
    model.write_text(UNUSED_DIMENSION)
    assert front.main(['check', str(model)]) == 0, 'advice is not a refusal'
    out, err = capsys.readouterr()
    assert "dimension 'spare' is never used" in out
    assert err == ''


def test_check_puts_a_refusal_on_stderr_with_exit_status_one(tmp_path, capsys):
    model = tmp_path / 'm.yaml'
    model.write_text(UNUSED_DIMENSION.replace('sum(p * c)', 'sum(p * nope)'))
    assert front.main(['check', str(model)]) == 1
    out, err = capsys.readouterr()
    assert out == ''
    assert "'nope' not found" in err


def test_the_shell_front_costs_no_dependency():
    """It is stdlib argparse over `typeset`, and that is a decision.

    A framework — typer, click — would buy nothing this front uses: it has one
    command wearing three format names, generated by a loop, which is the shape
    decorator-per-command ergonomics do not help. Behind an optional extra it
    would be worse than stdlib, because `python -m math_spec latex` would stop
    working on a bare install while the docs still showed it. If that trade is
    ever worth making, this test is where the argument has to be made.
    """
    tree = ast.parse(Path(front.__file__).read_text())
    roots = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            roots |= {alias.name.split('.')[0] for alias in node.names}
        elif isinstance(node, ast.ImportFrom) and node.module:
            roots.add(node.module.split('.')[0])

    assert roots <= sys.stdlib_module_names | {'math_spec'}, f'the shell front grew a dependency: {roots}'


@pytest.mark.parametrize('fmt', sorted(FORMATS))
def test_every_format_renders_to_stdout_and_to_a_file(fmt, tmp_path, capsys):
    """Both outputs, because `-o` is the one a Makefile actually uses."""
    assert front.main([fmt, MODEL]) == 0
    streamed = capsys.readouterr().out
    assert streamed.strip(), f'{fmt} rendered nothing'

    out = tmp_path / f'model.{fmt}'
    assert front.main([fmt, MODEL, '-o', str(out)]) == 0
    assert out.read_text() == streamed


def test_a_format_nothing_can_render_is_refused_rather_than_guessed():
    """The failure worth excluding is a front that writes an empty file.

    In a Makefile that reads as success, and the next step compiles nothing.
    """
    with pytest.raises(SystemExit) as raised:
        front.main(['docx', MODEL])
    assert raised.value.code != 0


def test_no_verb_binds_data():
    """The rule the module docstring states, checked rather than asserted.

    No verb takes `--source` or `--coords`: a source mapping in flags is a
    dict with worse errors, and a typed axis cannot be spelled in flags at
    all. If a verb ever needs data, it takes one path to a run manifest, and
    that argument gets made before this test changes.
    """
    banned = {'--source', '--coords', '--data'}
    for name, verb in _verbs().items():
        flags = {option for action in verb._actions for option in action.option_strings}
        assert not (flags & banned), f'{name} binds data: {sorted(flags & banned)}'
