# SPDX-FileCopyrightText: math-spec Contributors
#
# SPDX-License-Identifier: MIT

"""The typeset shell front — `python -m math_spec <format> model.yaml`.

Forty-eight lines that nothing exercised until now, which is the wrong ratio in
a repo that pins its Python surface against a table in both directions. What is
checked here is the *design* rather than argparse: that the verbs are read off
`FORMATS` rather than listed twice, that the front costs no dependency, that no
verb binds data, and that a format nothing can render is refused rather than
written as an empty file.

`main` takes its argv and `parser` hands back the verbs, so none of this needs a
subprocess or a scrape of help text.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

import pytest

import math_spec.__main__ as front
from math_spec.typesetting import FORMATS
from tests.typesetting import golden

#: The golden model, not `examples/dispatch.yaml`: the CLI travels with the
#: renderer and this fixture travels with both, where the gallery stays.
MODEL = str(golden.MODEL)


def _verbs() -> set[str]:
    """The subcommands the front actually registered.

    Read off the parser rather than the ``--help`` text: a format named in a
    help *sentence* would satisfy a substring check without a verb existing.
    """
    for action in front.parser()._actions:
        if isinstance(action, argparse._SubParsersAction):
            return set(action.choices)
    raise AssertionError('the front registered no subcommands at all')


def test_the_verbs_are_the_formats_and_nothing_else():
    """The one claim the module makes about itself, in both directions.

    The verbs are built by looping over `FORMATS`, so a new typeset format
    arrives with its verb already written and there is no second list to
    forget. A verb hand-added here, or a format quietly dropped, breaks this.
    """
    assert _verbs() == set(FORMATS)


def test_the_shell_front_costs_no_dependency():
    """It is stdlib argparse over `typeset`, and that is a decision.

    A framework — typer, click — would buy nothing this front uses: it has one
    command wearing three format names, generated by a loop, which is the shape
    decorator-per-command ergonomics do not help. Behind an optional extra it
    would be worse than stdlib, because `python -m math_spec latex` would stop
    working on a bare install while the docs still showed it. If that trade is
    ever worth making, this test is where the argument has to be made.
    """
    tree = ast.parse(Path(front.__file__).read_text())
    roots = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            roots |= {alias.name.split('.')[0] for alias in node.names}
        elif isinstance(node, ast.ImportFrom) and node.module:
            roots.add(node.module.split('.')[0])

    assert roots <= sys.stdlib_module_names | {'math_spec'}, f'the shell front grew a dependency: {roots}'


@pytest.mark.parametrize('fmt', sorted(FORMATS))
def test_every_format_renders_to_stdout_and_to_a_file(fmt, tmp_path, capsys):
    """Both sinks, because `-o` is the one a Makefile actually uses."""
    assert front.main([fmt, MODEL]) == 0
    streamed = capsys.readouterr().out
    assert streamed.strip(), f'{fmt} rendered nothing'

    out = tmp_path / f'model.{fmt}'
    assert front.main([fmt, MODEL, '-o', str(out)]) == 0
    assert out.read_text() == streamed, 'the file and the stream disagree'


def test_a_format_nothing_can_render_is_refused_rather_than_guessed():
    """The failure worth excluding is a front that writes an empty file.

    In a Makefile that reads as success, and the next step compiles nothing.
    """
    with pytest.raises(SystemExit) as raised:
        front.main(['docx', MODEL])
    assert raised.value.code != 0


def test_no_verb_binds_data():
    """The rule the module docstring states, checked rather than asserted.

    No verb takes `--source` or `--coords`: a source mapping in flags is a
    dict with worse errors, and a typed axis cannot be spelled in flags at
    all. If a verb ever needs data, it takes one path to a run manifest, and
    that argument gets made before this test changes.
    """
    banned = {'--source', '--coords', '--data'}
    for action in front.parser()._actions:
        if isinstance(action, argparse._SubParsersAction):
            for name, verb in action.choices.items():
                flags = {option for verb_action in verb._actions for option in verb_action.option_strings}
                assert not (flags & banned), f'{name} binds data: {sorted(flags & banned)}'
