#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=5

REPO="energy-models/math-spec"
ORG="energy-models"

# Preflight: everything below needs an authenticated gh with admin on the repo.
if ! command -v gh >/dev/null 2>&1; then
  printf 'This wizard drives the GitHub CLI. Install it first: https://cli.github.com\n'
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  printf 'Not logged in. Run: gh auth login\n'
  exit 1
fi
if [[ "$(gh api "repos/$REPO" --jq .permissions.admin 2>/dev/null)" != "true" ]]; then
  printf 'You need admin on %s to do any of this.\n' "$REPO"
  exit 1
fi
# `set_secret` in the library above resolves the repository from the working
# directory, so the wizard has to run from inside the clone.
if [[ "$(git rev-parse --show-toplevel 2>/dev/null)" == "" ]]; then
  printf 'Run this from inside the math-spec clone.\n'
  exit 1
fi

banner "release-please: GitHub App + branch rules"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Register the GitHub App"
say "release.yml mints a token from this app. Without it the action falls back"
say "to GITHUB_TOKEN, whose PRs run no CI and whose tags start no workflow —"
say "so releases would get no wheel."
printf '\n'
open_url "https://github.com/organizations/$ORG/settings/apps/new"
step "Name it something like 'math-spec release-please'. Names are global, so"
step "  add a suffix if it is taken."
step "Homepage URL: https://github.com/$REPO  (any URL, it is only a label)"
step "Under Webhook, UNTICK 'Active'. Leaving it on demands a webhook URL."
step "Repository permissions — set exactly two, leave every other at 'No access':"
step "    Contents      → Read and write"
step "    Pull requests → Read and write"
step "'Where can this GitHub App be installed?' → Only on this account"
step "Click 'Create GitHub App'."
printf '\n'
note "The next page is the app's settings, with 'Client ID' near the top."
note "That is the Client ID, not the App ID — release.yml passes it as client-id."
ask APP_CLIENT_ID "Paste the Client ID:"
if [[ -z "$APP_CLIENT_ID" ]]; then
  warn "no Client ID entered; re-run this wizard once you have it"
  exit 1
fi
write_env APP_CLIENT_ID "$APP_CLIENT_ID"
set_secret APP_CLIENT_ID "$APP_CLIENT_ID"
pause "Press Enter for the private key."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Generate the private key"
say "The key is a multi-line .pem, so this stage reads it from the downloaded"
say "file rather than asking you to paste it."
printf '\n'
step "Still on the app's settings page, scroll to 'Private keys'."
step "Click 'Generate a private key'. A .pem downloads immediately."
printf '\n'
DEFAULT_PEM=""
for candidate in "$HOME"/Downloads/*.private-key.pem; do
  [[ -f "$candidate" ]] && DEFAULT_PEM="$candidate"
done
if [[ -n "$DEFAULT_PEM" ]]; then
  note "found: $DEFAULT_PEM"
  note "Press Enter to use it, or type a different path."
fi
printf '  %sPath to the .pem:%s ' "$BOLD" "$RESET"
read -r PEM_PATH || true
[[ -z "$PEM_PATH" && -n "$DEFAULT_PEM" ]] && PEM_PATH="$DEFAULT_PEM"
PEM_PATH="${PEM_PATH/#\~/$HOME}"
if [[ ! -f "$PEM_PATH" ]]; then
  warn "no file at '$PEM_PATH'"
  SKIPPED+=("GitHub secret APP_PRIVATE_KEY (gh secret set APP_PRIVATE_KEY < your-key.pem)")
elif ! grep -q "BEGIN RSA PRIVATE KEY\|BEGIN PRIVATE KEY" "$PEM_PATH"; then
  warn "'$PEM_PATH' does not look like a PEM private key"
  SKIPPED+=("GitHub secret APP_PRIVATE_KEY (gh secret set APP_PRIVATE_KEY < your-key.pem)")
elif gh secret set APP_PRIVATE_KEY --repo "$REPO" < "$PEM_PATH"; then
  WRITTEN_SECRET+=("APP_PRIVATE_KEY")
  printf '  %s✓ set%s GitHub secret APP_PRIVATE_KEY\n' "$GREEN" "$RESET"
  printf '\n'
  if confirm "Delete the local .pem now that GitHub has it?"; then
    rm -f "$PEM_PATH" && note "deleted $PEM_PATH"
  else
    warn "keep it out of the repo and out of any backup you share"
  fi
else
  warn "gh could not set APP_PRIVATE_KEY"
  SKIPPED+=("GitHub secret APP_PRIVATE_KEY (gh secret set APP_PRIVATE_KEY < your-key.pem)")
fi
pause "Press Enter to install the app."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Install the app on $REPO"
say "An app with permissions but no installation grants nothing."
printf '\n'
open_url "https://github.com/organizations/$ORG/settings/apps"
step "Open your new app, then 'Install App' in the left sidebar."
step "Click Install next to $ORG."
step "Choose 'Only select repositories' → select math-spec → Install."
printf '\n'
pause "Press Enter once it is installed."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Allow auto-merge on the repository"
say "release.yml's alpha step calls 'gh pr merge --auto'. That command fails"
say "outright when the repository does not permit auto-merge."
printf '\n'
if gh api -X PATCH "repos/$REPO" -F allow_auto_merge=true >/dev/null 2>&1; then
  printf '  %s✓ enabled%s allow_auto_merge\n' "$GREEN" "$RESET"
else
  warn "could not enable it via the API"
  SKIPPED+=("Allow auto-merge (Settings → General → Pull Requests)")
  open_url "https://github.com/$REPO/settings"
  step "Settings → General → Pull Requests → tick 'Allow auto-merge'."
  pause "Press Enter once ticked."
fi
pause "Press Enter to verify."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Reading back what GitHub actually has, rather than what we just sent."
printf '\n'
SECRETS=$(gh api "repos/$REPO/actions/secrets" --jq '[.secrets[].name] | join(" ")' 2>/dev/null || echo "")
for want in APP_CLIENT_ID APP_PRIVATE_KEY; do
  if printf '%s' "$SECRETS" | grep -qw "$want"; then
    printf '  %s✓%s secret %s\n' "$GREEN" "$RESET" "$want"
  else
    printf '  %s✗%s secret %s is missing\n' "$RED" "$RESET" "$want"
  fi
done
if [[ "$(gh api "repos/$REPO" --jq .allow_auto_merge 2>/dev/null)" == "true" ]]; then
  printf '  %s✓%s auto-merge allowed\n' "$GREEN" "$RESET"
else
  printf '  %s✗%s auto-merge is still off\n' "$RED" "$RESET"
fi
printf '\n'
note "The app's own installation cannot be read with your user token, so it is"
note "not checked here. The real proof is the next merge to main: release.yml"
note "should open a release PR with no 'falling back to GITHUB_TOKEN' warning,"
note "and that PR should run CI."
printf '\n'
warn "Do NOT require status checks on main until you have seen that happen."
note "A release PR opened with GITHUB_TOKEN triggers no workflows, so required"
note "checks would never report and auto-merge would wait on them forever. The"
note "command to run afterwards is in RELEASING.md."

finish
